### ISSUE TITLE
55. Fix frontend background images not building correctly.

### ISSUE THREAD

**Issue by KajFromHH** [Ryhma-RED-Ohjelmistoprojekti-2/s24RyhmaREDfrontend#15]
For compiling of frontend, we need add backgrounds to directory and fix the code (CSS reference) so that compiled frontend is published correctly.

Also, picture format must be webp. It loads much faster.

**Comment by Textiili** [comment]
I put the image to /assets and imported the image in App.jsx (import backgroundImage from './assets/app_background.webp') as this hashes the image and allows better performance. Problems that appeared were result of local difference in pathing when base in vite,config was configurated differently.
