### ISSUE TITLE
62. Fix media queries and check background's responsive. I.e. good image quality and no white bar at bottom.

### ISSUE THREAD

**Issue by Textiili** [Ryhma-RED-Ohjelmistoprojekti-2/s24RyhmaREDfrontend#19]
There is media query problem for at least 1024px wide PCs and additional refinement would be needed all around.

**Comment by KajFromHH** [comment]
Make backgrounds mobile and tablet file's screen size more fitted when responsive. Just being default 1920 X 1080 causes image quality problems. For example, fix white bar at buttom, make "cover" in css.
